"""Tiny PDF generator using reportlab. Produces real PDFs (parseable by any PDF
reader) so the classify/validate step in the orchestrator has something
non-trivial to look at."""
from __future__ import annotations

from io import BytesIO

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


def make_pdf(*, carrier: str, doc_type: str, policy_number: str, insured_name: str, issued_on: str) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    c.setFont("Helvetica-Bold", 18)
    c.drawString(72, height - 72, f"{carrier} — {doc_type.replace('_', ' ').title()}")

    c.setFont("Helvetica", 11)
    y = height - 110
    lines = [
        f"Policy number : {policy_number}",
        f"Insured name  : {insured_name}",
        f"Document type : {doc_type}",
        f"Issued on     : {issued_on}",
        "",
        "This is a mock document generated for Fideon OS doc-retrieval testing.",
        "It contains no real policy data.",
    ]
    for line in lines:
        c.drawString(72, y, line)
        y -= 18

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(72, 72, f"Generated by mock-carriers/{carrier}")
    c.save()
    return buf.getvalue()
