-- ============================================================================
-- Fideon OS — COMBINED migrations (single-file apply)
-- Generated by concatenating supabase/migrations/*.sql in lexicographic order.
-- Run ONCE against a FRESH database (e.g. paste into the Supabase SQL editor).
-- Wrapped in a single transaction: if any statement fails, NOTHING is applied.
-- Do NOT edit here — edit the source files in migrations/ and regenerate.
-- ============================================================================

BEGIN;

-- ============================================================================
-- >>> 20260522010000_create_users.sql
-- ============================================================================
-- public.users — central identity table (replaces auth.users for all app logic)
-- FastAPI owns the entire auth layer; Supabase is DB-only.
-- See: backend/docs/Auth_Module_Plan.md §2.1

CREATE TABLE public.users (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email             TEXT        NOT NULL UNIQUE,
  password_hash     TEXT        NOT NULL,
  status            TEXT        NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('active','pending','locked','suspended')),
  email_verified_at TIMESTAMPTZ,
  failed_attempts   INT         NOT NULL DEFAULT 0,
  locked_until      TIMESTAMPTZ,
  full_name         TEXT,
  last_sign_in_at   TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX users_email_idx  ON public.users (email);
CREATE INDEX users_status_idx ON public.users (status);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010100_create_otp_codes.sql
-- ============================================================================
-- public.otp_codes — transient OTP state, separate from users
-- One row per user (UNIQUE). Deleted on successful verify, expiry, or max attempts.
-- See: backend/docs/Auth_Module_Plan.md §2.2

CREATE TABLE public.otp_codes (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  otp_code_hash TEXT        NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  attempt_count INT         NOT NULL DEFAULT 0,
  resend_count  INT         NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX otp_codes_user_id_idx ON public.otp_codes (user_id);

ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010200_create_invites.sql
-- ============================================================================
-- public.invites — invite-only signup gate
-- Raw token only in the email link; DB stores SHA-256 hash only.
-- See: backend/docs/Auth_Module_Plan.md §2.3

CREATE TABLE public.invites (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash  TEXT        NOT NULL UNIQUE,
  email       TEXT        NOT NULL,
  status      TEXT        NOT NULL DEFAULT 'PENDING'
              CHECK (status IN ('PENDING','ACCEPTED','EXPIRED','REVOKED')),
  invited_by  UUID        REFERENCES public.users(id),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '48 hours',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX invites_token_hash_idx ON public.invites (token_hash);
CREATE INDEX invites_email_idx      ON public.invites (email);
CREATE INDEX invites_status_idx     ON public.invites (status);

ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010300_alter_user_roles_custom_auth.sql
-- ============================================================================
-- Create user_roles if it doesn't exist (fresh self-hosted Supabase won't have it).
-- Then re-point user_id FK from auth.users → public.users.
-- Schema: one role per user, enforced by UNIQUE(user_id).
-- See: backend/docs/Auth_Module_Plan.md §2.4

CREATE TABLE IF NOT EXISTS public.user_roles (
  id         UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID  NOT NULL,
  role       TEXT  NOT NULL DEFAULT 'user'
             CHECK (role IN ('user','admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_roles_user_id_idx ON public.user_roles (user_id);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Drop old data (auth.users UUIDs won't match public.users)
TRUNCATE public.user_roles;

-- Drop old constraints if migrating from previous Supabase auth setup
ALTER TABLE public.user_roles
  DROP CONSTRAINT IF EXISTS user_roles_user_id_role_key;
ALTER TABLE public.user_roles
  DROP CONSTRAINT IF EXISTS user_roles_user_id_fkey;
ALTER TABLE public.user_roles
  DROP CONSTRAINT IF EXISTS user_roles_user_id_unique;

-- Add FK to public.users
ALTER TABLE public.user_roles
  ADD CONSTRAINT user_roles_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

-- One role per user
ALTER TABLE public.user_roles
  ADD CONSTRAINT user_roles_user_id_unique UNIQUE (user_id);

-- Drop old RLS policies
DROP POLICY IF EXISTS "Users can view their own roles" ON public.user_roles;
DROP POLICY IF EXISTS "Admins can manage all roles"    ON public.user_roles;

-- Only service_role (FastAPI backend) may read or write roles
DROP POLICY IF EXISTS user_roles_service ON public.user_roles;
CREATE POLICY user_roles_service ON public.user_roles
  FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ============================================================================
-- >>> 20260522010400_create_user_devices.sql
-- ============================================================================
-- public.user_devices — device fingerprinting and geo anomaly tracking
-- See: backend/docs/Auth_Module_Plan.md §2.5

CREATE TABLE public.user_devices (
  id               UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  fingerprint_hash TEXT    NOT NULL,
  ip_address       TEXT,
  country_code     CHAR(2),
  user_agent       TEXT,
  is_trusted       BOOLEAN NOT NULL DEFAULT false,
  last_seen_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ DEFAULT now(),
  UNIQUE (user_id, fingerprint_hash)
);

CREATE INDEX user_devices_user_id_idx ON public.user_devices (user_id);

ALTER TABLE public.user_devices ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010500_create_refresh_tokens.sql
-- ============================================================================
-- public.refresh_tokens — JWT refresh token rotation
-- Raw token only in HttpOnly cookie; DB stores SHA-256 hash.
-- Replay detection: if revoked token is reused, revoke ALL user tokens.
-- See: backend/docs/Auth_Module_Plan.md §2.6

CREATE TABLE public.refresh_tokens (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash  TEXT    NOT NULL UNIQUE,
  jti         TEXT    NOT NULL UNIQUE,
  revoked     BOOLEAN NOT NULL DEFAULT false,
  expires_at  TIMESTAMPTZ NOT NULL,
  device_info JSONB,
  ip_address  TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX refresh_tokens_user_id_idx ON public.refresh_tokens (user_id);

ALTER TABLE public.refresh_tokens ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010600_create_password_reset_tokens.sql
-- ============================================================================
-- public.password_reset_tokens — forgot-password flow
-- 15-minute TTL. Token hash only stored; raw token only in the email link.
-- See: backend/docs/Auth_Module_Plan.md §2.7

CREATE TABLE public.password_reset_tokens (
  id               UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reset_token_hash TEXT    NOT NULL UNIQUE,
  expires_at       TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '15 minutes',
  used             BOOLEAN NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.password_reset_tokens ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010700_create_password_history.sql
-- ============================================================================
-- public.password_history — last-3 password reuse check (Argon2id hashes)
-- Prune trigger keeps at most 3 rows per user.
-- See: backend/docs/Auth_Module_Plan.md §2.8

CREATE TABLE public.password_history (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.prune_password_history()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM public.password_history
  WHERE user_id = NEW.user_id
    AND id NOT IN (
      SELECT id FROM public.password_history
      WHERE user_id = NEW.user_id
      ORDER BY created_at DESC
      LIMIT 3
    );
  RETURN NEW;
END;
$$;

CREATE TRIGGER prune_password_history_trigger
  AFTER INSERT ON public.password_history
  FOR EACH ROW EXECUTE FUNCTION public.prune_password_history();

ALTER TABLE public.password_history ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522010800_alter_audit_logs_custom_auth.sql
-- ============================================================================
-- Create audit_logs if it doesn't exist (fresh self-hosted Supabase won't have it).
-- Then re-point the user_id FK from auth.users → public.users.
-- See: backend/docs/Auth_Module_Plan.md §2.9

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID,
  action        TEXT        NOT NULL,
  resource_type TEXT,
  resource_id   TEXT,
  ip_address    TEXT,
  user_agent    TEXT,
  details       JSONB       NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_logs_user_id_idx  ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS audit_logs_action_idx   ON public.audit_logs (action);
CREATE INDEX IF NOT EXISTS audit_logs_created_idx  ON public.audit_logs (created_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Clear any existing rows (auth.users UUIDs won't match public.users)
TRUNCATE public.audit_logs;

ALTER TABLE public.audit_logs
  DROP CONSTRAINT IF EXISTS audit_logs_user_id_fkey;

ALTER TABLE public.audit_logs
  ADD CONSTRAINT audit_logs_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Enforce INSERT-only at the DB role level (run against the Supabase app role FastAPI uses)
-- REVOKE UPDATE, DELETE ON public.audit_logs FROM authenticator;

-- Drop old RLS policies
DROP POLICY IF EXISTS "Admins can view all audit logs"      ON public.audit_logs;
DROP POLICY IF EXISTS "Users can view their own audit logs" ON public.audit_logs;
DROP POLICY IF EXISTS "System can insert audit logs"        ON public.audit_logs;

-- Only service_role (FastAPI backend) may read or write audit logs
DROP POLICY IF EXISTS audit_logs_service ON public.audit_logs;
CREATE POLICY audit_logs_service ON public.audit_logs
  FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ============================================================================
-- >>> 20260522010900_create_electron_service_tokens.sql
-- ============================================================================
-- public.electron_service_tokens — long-lived service tokens for Electron main process
-- 30-day TTL. Stored in OS keychain (Windows Credential Manager / macOS Keychain).
-- Web logout does NOT revoke these — separate token family from JWT refresh tokens.
-- See: backend/docs/Auth_Module_Plan.md §2.10

CREATE TABLE public.electron_service_tokens (
  id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT    NOT NULL UNIQUE,
  device_id  UUID    REFERENCES public.user_devices(id),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked    BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.electron_service_tokens ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- >>> 20260522011000_seed_first_admin.sql
-- ============================================================================
-- First admin user is seeded via supabase/seed_fideon_admin.sql (run separately after migrations).
-- This migration intentionally left as a no-op placeholder.
-- See: backend/docs/Auth_Module_Plan.md §6 Phase 1
SELECT 1;


-- ============================================================================
-- >>> 20260522020000_create_agents.sql
-- ============================================================================
-- public.agents — agent catalog (marketplace)
-- current_version_id is set after agent_versions rows are inserted (see 022_seed_agent_versions).
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agents (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword              TEXT        NOT NULL UNIQUE,
  name                 TEXT        NOT NULL,
  description          TEXT,
  domain               TEXT        NOT NULL,
  tagline              TEXT,
  icon_asset_file_name TEXT,
  current_version_id   UUID,       -- FK added after agent_versions exists; see constraint below
  status               TEXT        NOT NULL DEFAULT 'coming_soon'
                       CHECK (status IN ('live','beta','coming_soon','deprecated')),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX agents_keyword_idx ON public.agents (keyword);
CREATE INDEX agents_domain_idx  ON public.agents (domain);
CREATE INDEX agents_status_idx  ON public.agents (status);

ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER agents_updated_at
  BEFORE UPDATE ON public.agents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020100_create_agent_versions.sql
-- ============================================================================
-- public.agent_versions — versioned prompts, schemas, and rules per agent
-- Never mutate an existing row; add a new version row instead.
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agent_versions (
  id                        UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id                  UUID        NOT NULL REFERENCES public.agents(id) ON DELETE CASCADE,
  version                   TEXT        NOT NULL,
  prompt_template           TEXT,
  narrative_prompt_template TEXT,
  pydantic_rules_template   TEXT,
  input_schema              JSONB,
  output_schema             JSONB,
  is_active                 BOOLEAN     NOT NULL DEFAULT true,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (agent_id, version)
);

CREATE INDEX agent_versions_agent_id_idx ON public.agent_versions (agent_id);

ALTER TABLE public.agent_versions ENABLE ROW LEVEL SECURITY;

-- Back-pointer FK: agents.current_version_id → agent_versions(id)
ALTER TABLE public.agents
  ADD CONSTRAINT agents_current_version_id_fkey
    FOREIGN KEY (current_version_id) REFERENCES public.agent_versions(id);


-- ============================================================================
-- >>> 20260522020200_create_agent_dashboard_templates.sql
-- ============================================================================
-- public.agent_dashboard_templates — per-agent widget config (one row per agent)
-- widgets JSONB drives every KPI tile; zero frontend code changes to add/edit tiles.
-- tabs JSONB is non-null only for multi-tab agents (e.g. Loss Run Reporting).
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agent_dashboard_templates (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id              UUID        NOT NULL UNIQUE REFERENCES public.agents(id) ON DELETE CASCADE,
  widgets               JSONB       NOT NULL DEFAULT '[]',
  tabs                  JSONB,
  comparison_period_days INT        NOT NULL DEFAULT 30,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.agent_dashboard_templates ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER agent_dashboard_templates_updated_at
  BEFORE UPDATE ON public.agent_dashboard_templates
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020300_create_user_agents.sql
-- ============================================================================
-- public.user_agents — which users have access to which agents (activations)
-- Replaces the old activated_models table (different name, different schema).
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.user_agents (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  agent_id           UUID        NOT NULL REFERENCES public.agents(id),
  current_version_id UUID        REFERENCES public.agent_versions(id),
  model_name         TEXT        NOT NULL,
  domain             TEXT        NOT NULL,
  activated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_active          BOOLEAN     NOT NULL DEFAULT true,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, agent_id)
);

CREATE INDEX user_agents_user_id_idx  ON public.user_agents (user_id);
CREATE INDEX user_agents_agent_id_idx ON public.user_agents (agent_id);

ALTER TABLE public.user_agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_agents_user ON public.user_agents
  FOR ALL USING (user_id = auth.uid());

CREATE TRIGGER user_agents_updated_at
  BEFORE UPDATE ON public.user_agents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020400_create_user_agent_stats.sql
-- ============================================================================
-- public.user_agent_stats — pre-aggregated KPI stats per user per agent
-- Written by the FastAPI runner on every run completion. Read is always O(1).
-- Never run GROUP BY at read time; aggregate only at write time.
-- See: backend/docs/pod_structure.md §3 Group 1 + §5 Write Path

CREATE TABLE public.user_agent_stats (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_agent_id UUID        NOT NULL UNIQUE REFERENCES public.user_agents(id) ON DELETE CASCADE,
  stats         JSONB       NOT NULL DEFAULT '{}',
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.user_agent_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY uas_user ON public.user_agent_stats
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_agents ua
      WHERE ua.id = user_agent_id AND ua.user_id = auth.uid()
    )
  );


-- ============================================================================
-- >>> 20260522020500_create_agent_runs.sql
-- ============================================================================
-- public.agent_runs — per-run execution log
-- metrics JSONB: per-run KPIs (Layer 3). activity JSONB: Activity tab feed entry (Layer 4).
-- Both written at run completion. human_in_the_loop flag only; detail in agent_run_approvals.
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agent_runs (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES public.users(id),
  agent_id         UUID        NOT NULL REFERENCES public.agents(id),
  version_used     UUID        REFERENCES public.agent_versions(id),
  status           TEXT        NOT NULL DEFAULT 'running'
                   CHECK (status IN ('running','complete','failed')),
  input            JSONB,
  output           JSONB,
  confidence       DECIMAL(5,2),
  metrics          JSONB,
  activity         JSONB,
  human_in_the_loop BOOLEAN    NOT NULL DEFAULT false,
  started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at      TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Covers Activity tab (Q3), Trends tab (Q7), write-path pre-flight
CREATE INDEX agent_runs_user_agent_started_idx
  ON public.agent_runs (user_id, agent_id, started_at DESC);
CREATE INDEX agent_runs_agent_id_idx ON public.agent_runs (agent_id);
CREATE INDEX agent_runs_status_idx   ON public.agent_runs (status);

ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY agent_runs_user ON public.agent_runs
  FOR ALL USING (user_id = auth.uid());

CREATE TRIGGER agent_runs_updated_at
  BEFORE UPDATE ON public.agent_runs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020600_create_agent_run_approvals.sql
-- ============================================================================
-- public.agent_run_approvals — HITL approval detail (separate from run row)
-- agent_runs.human_in_the_loop is a flag only; full approval state lives here.
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agent_run_approvals (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id      UUID        NOT NULL REFERENCES public.agent_runs(id) ON DELETE CASCADE,
  user_id     UUID        NOT NULL REFERENCES public.users(id),
  hitl_status TEXT        NOT NULL DEFAULT 'pending'
              CHECK (hitl_status IN ('pending','approved','rejected','escalated')),
  decision    TEXT,
  reviewer_id UUID        REFERENCES public.users(id),
  reviewed_at TIMESTAMPTZ,
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ara_run_id_idx  ON public.agent_run_approvals (run_id);
CREATE INDEX ara_user_id_idx ON public.agent_run_approvals (user_id);
CREATE INDEX ara_status_idx  ON public.agent_run_approvals (hitl_status);

ALTER TABLE public.agent_run_approvals ENABLE ROW LEVEL SECURITY;

CREATE POLICY ara_user ON public.agent_run_approvals
  FOR SELECT USING (user_id = auth.uid());

CREATE TRIGGER agent_run_approvals_updated_at
  BEFORE UPDATE ON public.agent_run_approvals
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020700_create_agent_access_requests.sql
-- ============================================================================
-- public.agent_access_requests — marketplace agent access requests
-- For existing Fideon marketplace agents only. For user-built custom agents → custom_agent_requests.
-- On approval: admin sets is_active=true in user_agents for this user+agent pair.
-- See: backend/docs/pod_structure.md §3 Group 1

CREATE TABLE public.agent_access_requests (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  agent_id         UUID        NOT NULL REFERENCES public.agents(id),
  model_name       TEXT        NOT NULL,
  status           TEXT        NOT NULL DEFAULT 'submitted'
                   CHECK (status IN ('submitted','approved','rejected')),
  requested_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at      TIMESTAMPTZ,
  reviewed_by      UUID        REFERENCES public.users(id),
  rejection_reason TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX aar_user_id_idx  ON public.agent_access_requests (user_id);
CREATE INDEX aar_agent_id_idx ON public.agent_access_requests (agent_id);
CREATE INDEX aar_status_idx   ON public.agent_access_requests (status);

ALTER TABLE public.agent_access_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY aar_user ON public.agent_access_requests
  FOR SELECT USING (user_id = auth.uid());


-- ============================================================================
-- >>> 20260522020800_create_custom_agent_requests.sql
-- ============================================================================
-- public.custom_agent_requests — user-initiated custom agent build requests
-- Carries the full build pipeline lifecycle: submitted → in_review → building → testing → installed.
-- Distinct from agent_access_requests (marketplace agents) and custom_pod_requests (old table).
-- See: backend/docs/pod_structure.md §3 Group 2

CREATE TABLE public.custom_agent_requests (
  id                       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                  UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title                    TEXT        NOT NULL,
  sop_text                 TEXT,
  sop_file_url             TEXT,
  target_carriers          TEXT[],
  priority                 TEXT        NOT NULL DEFAULT 'normal'
                           CHECK (priority IN ('low','normal','high','urgent')),
  expected_outcome         TEXT,
  phone_no                 TEXT,
  desired_by               DATE,
  status                   TEXT        NOT NULL DEFAULT 'submitted'
                           CHECK (status IN ('submitted','in_review','building','testing','installed')),
  status_history           JSONB       NOT NULL DEFAULT '[]',
  assigned_admin_id        UUID        REFERENCES public.users(id),
  reviewed_at              TIMESTAMPTZ,
  reviewed_by              UUID        REFERENCES public.users(id),
  rejection_reason         TEXT,
  custom_agent_id          UUID,  -- FK to custom_agents added in migration 20260523000300
  installed_user_agent_id  UUID        REFERENCES public.user_agents(id),
  installed_at             TIMESTAMPTZ,
  requested_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX car_user_id_idx ON public.custom_agent_requests (user_id);
CREATE INDEX car_status_idx  ON public.custom_agent_requests (status);

ALTER TABLE public.custom_agent_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY car_user ON public.custom_agent_requests
  FOR SELECT USING (user_id = auth.uid());

CREATE TRIGGER custom_agent_requests_updated_at
  BEFORE UPDATE ON public.custom_agent_requests
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020850_create_integrations.sql
-- ============================================================================
-- public.carrier_connections + public.ams_connections — Group 3 Integrations.
-- Authoritative schema base: backend/docs/pod_structure.md §3 Group 3.
-- Created BEFORE 20260522020900_migrate_carrier_connections.sql.
-- Credentials are stored as *_ciphertext (encrypted at the app layer); never plaintext.
--
-- GLOBAL / ADMIN-MANAGED: credentials are set ONCE by an admin and apply to ALL users
-- automatically. There is exactly one row per carrier_id / ams_id (no per-user rows).
-- `set_by` records which admin configured it.

-- ── carrier_connections — carrier portal credentials (global, admin-set) ──────
CREATE TABLE IF NOT EXISTS public.carrier_connections (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  carrier_id          TEXT        NOT NULL UNIQUE,   -- one global row per carrier
  set_by              UUID        REFERENCES public.users(id) ON DELETE SET NULL,  -- admin who set it
  username            TEXT,
  password_ciphertext TEXT,
  credential_token    TEXT,
  producer_codes      JSONB,
  extra               JSONB       NOT NULL DEFAULT '{}',   -- { portal_url, doc_types, sources, email_alias }
  status              TEXT        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','connected','error')),
  last_test_at        TIMESTAMPTZ,
  last_test_message   TEXT,
  last_synced_at      TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.carrier_connections ENABLE ROW LEVEL SECURITY;
-- service_role only; user scoping enforced in FastAPI (custom RS256 auth, no auth.uid()).
DROP POLICY IF EXISTS carrier_connections_service ON public.carrier_connections;
CREATE POLICY carrier_connections_service ON public.carrier_connections
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TRIGGER carrier_connections_updated_at
  BEFORE UPDATE ON public.carrier_connections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── ams_connections — AMS credentials (global, admin-set) ─────────────────────
CREATE TABLE IF NOT EXISTS public.ams_connections (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ams_id              TEXT        NOT NULL UNIQUE,   -- one global row per AMS
  set_by              UUID        REFERENCES public.users(id) ON DELETE SET NULL,  -- admin who set it
  auth_method         TEXT        NOT NULL DEFAULT 'credentials'
                      CHECK (auth_method IN ('credentials','sdk')),
  username            TEXT,
  password_ciphertext TEXT,
  api_key_ciphertext  TEXT,
  instance_url        TEXT,
  tenant_id           TEXT,
  credential_token    TEXT,
  extra               JSONB       NOT NULL DEFAULT '{}',   -- { db_name_sandbox, db_name_prod }
  status              TEXT        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','connected','error')),
  last_test_at        TIMESTAMPTZ,
  last_test_message   TEXT,
  last_synced_at      TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.ams_connections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ams_connections_service ON public.ams_connections;
CREATE POLICY ams_connections_service ON public.ams_connections
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TRIGGER ams_connections_updated_at
  BEFORE UPDATE ON public.ams_connections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522020900_migrate_carrier_connections.sql
-- ============================================================================
-- Absorb document_retrieval_configs into carrier_connections.extra JSONB.
-- carrier_connections already has an extra JSONB column; migrate sources, doc_types,
-- email_alias from document_retrieval_configs into it, then deprecate the old table.
-- See: backend/docs/pod_structure.md §9 Migration

-- NOTE: carrier_connections and document_retrieval_configs are NOT created in this
-- migration set — their schema/ownership is owned by a separate workstream (see
-- backend/docs/pending_tables.md). This migration is therefore guarded so a fresh DB
-- migrates cleanly when those tables are absent; it only runs the data move once both
-- tables actually exist.
-- NOTE: carrier_connections is now GLOBAL/admin-set (one row per carrier_id, no user_id);
-- doc-retrieval config lives in carrier_connections.extra. There is no per-user
-- document_retrieval_configs data to migrate. If a legacy table exists, just deprecate it.
DO $$
BEGIN
  IF to_regclass('public.document_retrieval_configs') IS NOT NULL THEN
    ALTER TABLE public.document_retrieval_configs
      RENAME TO document_retrieval_configs_deprecated;
  ELSE
    RAISE NOTICE 'No legacy document_retrieval_configs to deprecate.';
  END IF;
END $$;


-- ============================================================================
-- >>> 20260522021000_seed_agents.sql
-- ============================================================================
-- Seed the 6 live agents into public.agents.
-- Stable UUIDs used so agent_versions and dashboard_templates seeds can reference them.
-- current_version_id left NULL here; updated in 022_seed_agent_versions.
-- See: backend/docs/pod_structure.md §10 Agent Catalog Reference

INSERT INTO public.agents (id, keyword, name, description, domain, tagline, status)
VALUES
  (
    '10000000-0000-0000-0000-000000000001',
    'document-retrieval',
    'Document Retrieval',
    'Automatically retrieves loss runs, policies, endorsements, and renewals from carrier portals and email.',
    'insurance',
    'Pull documents from any carrier, automatically.',
    'live'
  ),
  (
    '10000000-0000-0000-0000-000000000002',
    'loss-run-reporting',
    'Loss Run Reporting',
    'Pulls loss run data from carrier portals and generates structured reports for renewal and new-business workflows.',
    'insurance',
    'From carrier portal to structured report in seconds.',
    'live'
  ),
  (
    '10000000-0000-0000-0000-000000000003',
    'policy-comparison',
    'Policy Comparison Engine',
    'Compares policy documents across carriers to surface coverage gaps, premium deltas, and recommendations.',
    'insurance',
    'Side-by-side coverage analysis, instantly.',
    'live'
  ),
  (
    '10000000-0000-0000-0000-000000000004',
    'quote-generation',
    'Quote Generation Agent',
    'Fetches and structures quotes from multiple carriers for a given risk profile.',
    'insurance',
    'Multi-carrier quotes, structured and ready to present.',
    'live'
  ),
  (
    '10000000-0000-0000-0000-000000000005',
    'coverage-validation',
    'Coverage Validation',
    'Validates active policies against client requirements and flags discrepancies for review.',
    'insurance',
    'Catch coverage gaps before they become claims.',
    'live'
  ),
  (
    '10000000-0000-0000-0000-000000000006',
    'renewal-review',
    'Renewal Review',
    'Prepares renewal packages by analysing expiring policies, flagging premium changes, and drafting client emails.',
    'insurance',
    'Renewal prep, automated end-to-end.',
    'live'
  )
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- >>> 20260522021100_seed_agent_versions.sql
-- ============================================================================
-- Seed v1.0.0 for each of the 6 live agents.
-- After inserting versions, back-fill agents.current_version_id.
-- See: backend/docs/pod_structure.md §10

INSERT INTO public.agent_versions
  (id, agent_id, version, is_active,
   input_schema, output_schema)
VALUES
  -- document-retrieval v1.0.0
  (
    '20000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000001',
    '1.0.0', true,
    '{"carrier_ids":{"type":"array","items":"string","required":true},"date_range":{"type":"object","required":true},"document_types":{"type":"array","items":"string","required":true,"enum":["renewal","endorsement","cancellation","loss_run","invoice"]},"email_alias":{"type":"string","required":false}}',
    '{"documents_synced":{"type":"number"},"sync_success":{"type":"boolean"},"retrieval_time_s":{"type":"number"},"carriers_hit":{"type":"number"},"failed":{"type":"number"},"doc_types":{"type":"object"},"completed_at":{"type":"timestamp"}}'
  ),
  -- loss-run-reporting v1.0.0
  (
    '20000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000002',
    '1.0.0', true,
    '{"carrier_ids":{"type":"array","items":"string","required":true},"policy_numbers":{"type":"array","items":"string","required":false},"date_range":{"type":"object","required":true},"include_open_claims":{"type":"boolean","required":false}}',
    '{"loss_runs_processed":{"type":"number"},"avg_loss_ratio_pct":{"type":"number"},"carriers_pulled":{"type":"number"},"open_claims":{"type":"number"},"avg_pull_time_s":{"type":"number"},"completed_at":{"type":"timestamp"}}'
  ),
  -- policy-comparison v1.0.0
  (
    '20000000-0000-0000-0000-000000000003',
    '10000000-0000-0000-0000-000000000003',
    '1.0.0', true,
    '{"policy_ids":{"type":"array","items":"string","required":true},"comparison_dimensions":{"type":"array","items":"string","required":false}}',
    '{"comparisons_run":{"type":"number"},"avg_coverage_score":{"type":"number"},"coverage_gaps_found":{"type":"number"},"avg_premium_delta_usd":{"type":"number"},"recommendations_acted_pct":{"type":"number"},"completed_at":{"type":"timestamp"}}'
  ),
  -- quote-generation v1.0.0
  (
    '20000000-0000-0000-0000-000000000004',
    '10000000-0000-0000-0000-000000000004',
    '1.0.0', true,
    '{"carrier_ids":{"type":"array","items":"string","required":true},"risk_profile":{"type":"object","required":true},"effective_date":{"type":"string","required":true}}',
    '{"quotes_generated":{"type":"number"},"bind_rate_pct":{"type":"number"},"avg_premium_usd":{"type":"number"},"avg_turnaround_s":{"type":"number"},"quoted_premium_usd":{"type":"number"},"completed_at":{"type":"timestamp"}}'
  ),
  -- coverage-validation v1.0.0
  (
    '20000000-0000-0000-0000-000000000005',
    '10000000-0000-0000-0000-000000000005',
    '1.0.0', true,
    '{"policy_ids":{"type":"array","items":"string","required":true},"client_requirements":{"type":"object","required":true}}',
    '{"policies_checked":{"type":"number"},"discrepancies_found":{"type":"number"},"avg_check_time_s":{"type":"number"},"auto_resolved":{"type":"number"},"pending_review":{"type":"number"},"completed_at":{"type":"timestamp"}}'
  ),
  -- renewal-review v1.0.0
  (
    '20000000-0000-0000-0000-000000000006',
    '10000000-0000-0000-0000-000000000006',
    '1.0.0', true,
    '{"policy_ids":{"type":"array","items":"string","required":true},"renewal_window_days":{"type":"number","required":false}}',
    '{"renewals_prepped":{"type":"number"},"avg_premium_delta_pct":{"type":"number"},"changes_flagged":{"type":"number"},"client_emails_drafted":{"type":"number"},"avg_prep_time_s":{"type":"number"},"completed_at":{"type":"timestamp"}}'
  )
ON CONFLICT (id) DO NOTHING;

-- Back-fill agents.current_version_id
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000001' WHERE id = '10000000-0000-0000-0000-000000000001';
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000002' WHERE id = '10000000-0000-0000-0000-000000000002';
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000003' WHERE id = '10000000-0000-0000-0000-000000000003';
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000004' WHERE id = '10000000-0000-0000-0000-000000000004';
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000005' WHERE id = '10000000-0000-0000-0000-000000000005';
UPDATE public.agents SET current_version_id = '20000000-0000-0000-0000-000000000006' WHERE id = '10000000-0000-0000-0000-000000000006';


-- ============================================================================
-- >>> 20260522021200_seed_agent_dashboard_templates.sql
-- ============================================================================
-- Seed dashboard widget configs for all 6 live agents.
-- widgets[] drives KPI tiles; tabs[] is non-null only for Loss Run Reporting.
-- See: backend/docs/pod_structure.md §3 agent_dashboard_templates + §4 Layer 1

INSERT INTO public.agent_dashboard_templates
  (id, agent_id, comparison_period_days, widgets, tabs)
VALUES

-- ── Document Retrieval ────────────────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000001',
  30,
  '[
    {"id":"documents_synced","type":"kpi_tile","field":"documents_synced","format":"number","header":"Documents Synced","footer":"Last 30 days","delta_field":"documents_synced_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":2000},"warn":{"gte":1000},"danger":{"lt":1000}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"sync_success_rate","type":"kpi_tile","field":"sync_success_rate","format":"percent","header":"Sync Success Rate","footer":"Percentage of successful syncs","delta_field":"sync_success_rate_delta_pts","delta_format":"absolute_pts","trend":true,"invert":false,"criteria":{"good":{"gte":95},"warn":{"gte":85},"danger":{"lt":85}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_retrieval_time_s","type":"kpi_tile","field":"avg_retrieval_time_s","format":"seconds","header":"Avg. Retrieval Time","footer":"Per document","delta_field":"avg_retrieval_time_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":15},"warn":{"lte":30},"danger":{"gt":30}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"carriers_connected","type":"kpi_tile","field":"carriers_connected","format":"number","header":"Carriers Connected","footer":"Active carrier portals","delta_field":"carriers_connected_delta","delta_format":"absolute","trend":false,"invert":false,"criteria":{"good":{"gte":20},"warn":{"gte":10},"danger":{"lt":10}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"failed_pulls","type":"kpi_tile","field":"failed_pulls","format":"number","header":"Failed Pulls","footer":"Lower is better","delta_field":"failed_pulls_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":20},"warn":{"lte":50},"danger":{"gt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
),

-- ── Loss Run Reporting (tabbed) ───────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000002',
  30,
  '[
    {"id":"loss_runs_processed","type":"kpi_tile","field":"loss_runs_processed","format":"number","header":"Loss Runs Processed","footer":"Last 30 days","delta_field":"loss_runs_processed_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":500},"warn":{"gte":200},"danger":{"lt":200}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_loss_ratio_pct","type":"kpi_tile","field":"avg_loss_ratio_pct","format":"percent","header":"Avg. Loss Ratio","footer":"Across processed runs","delta_field":"avg_loss_ratio_delta_pts","delta_format":"absolute_pts","trend":true,"invert":true,"criteria":{"good":{"lte":60},"warn":{"lte":80},"danger":{"gt":80}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"carriers_pulled","type":"kpi_tile","field":"carriers_pulled","format":"number","header":"Carriers Pulled","footer":"Active carrier sources","delta_field":"carriers_pulled_delta","delta_format":"absolute","trend":false,"invert":false,"criteria":{"good":{"gte":10},"warn":{"gte":5},"danger":{"lt":5}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"open_claims","type":"kpi_tile","field":"open_claims","format":"number","header":"Open Claims","footer":"Flagged for review","delta_field":"open_claims_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":50},"warn":{"lte":100},"danger":{"gt":100}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_pull_time_s","type":"kpi_tile","field":"avg_pull_time_s","format":"seconds","header":"Avg. Pull Time","footer":"Per loss run","delta_field":"avg_pull_time_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":20},"warn":{"lte":45},"danger":{"gt":45}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  '[
    {"id":"renewal_book","label":"Renewal book","widgets":[
      {"id":"portfolio_renewals_due_30d","type":"kpi_tile","field":"portfolio_renewals_due_30d","format":"number","header":"Renewals Due (30d)","footer":"Policies expiring within 30 days","delta_field":null,"delta_format":null,"trend":false,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
      {"id":"portfolio_renewals_due_90d","type":"kpi_tile","field":"portfolio_renewals_due_90d","format":"number","header":"Renewals Due (90d)","footer":"Policies expiring within 90 days","delta_field":null,"delta_format":null,"trend":false,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
      {"id":"loss_runs_received","type":"kpi_tile","field":"loss_runs_received","format":"number","header":"Loss Runs Received","footer":"Ready for renewal review","delta_field":"loss_runs_received_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":100},"warn":{"gte":50},"danger":{"lt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
    ]},
    {"id":"new_business","label":"New business","widgets":[
      {"id":"prospects_count","type":"kpi_tile","field":"prospects_count","format":"number","header":"Prospects","footer":"Active new-business prospects","delta_field":"prospects_count_delta","delta_format":"absolute","trend":true,"invert":false,"criteria":{"good":{"gte":20},"warn":{"gte":10},"danger":{"lt":10}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
    ]}
  ]'
),

-- ── Policy Comparison Engine ──────────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000003',
  '10000000-0000-0000-0000-000000000003',
  30,
  '[
    {"id":"comparisons_run","type":"kpi_tile","field":"comparisons_run","format":"number","header":"Comparisons Run","footer":"Last 30 days","delta_field":"comparisons_run_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":100},"warn":{"gte":50},"danger":{"lt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_coverage_score","type":"kpi_tile","field":"avg_coverage_score","format":"score","header":"Avg. Coverage Score","footer":"Out of 100","delta_field":"avg_coverage_score_delta","delta_format":"absolute","trend":true,"invert":false,"criteria":{"good":{"gte":80},"warn":{"gte":65},"danger":{"lt":65}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"coverage_gaps_found","type":"kpi_tile","field":"coverage_gaps_found","format":"number","header":"Coverage Gaps Found","footer":"Flagged across comparisons","delta_field":"coverage_gaps_found_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":10},"warn":{"lte":25},"danger":{"gt":25}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_premium_delta_usd","type":"kpi_tile","field":"avg_premium_delta_usd","format":"currency","header":"Avg. Premium Delta","footer":"vs. prior period","delta_field":null,"delta_format":null,"trend":false,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"recommendations_acted_pct","type":"kpi_tile","field":"recommendations_acted_pct","format":"percent","header":"Recommendations Acted","footer":"Of total recommendations","delta_field":"recommendations_acted_delta_pts","delta_format":"absolute_pts","trend":true,"invert":false,"criteria":{"good":{"gte":70},"warn":{"gte":50},"danger":{"lt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
),

-- ── Quote Generation Agent ────────────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000004',
  30,
  '[
    {"id":"quotes_generated","type":"kpi_tile","field":"quotes_generated","format":"number","header":"Quotes Generated","footer":"Last 30 days","delta_field":"quotes_generated_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":200},"warn":{"gte":100},"danger":{"lt":100}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"bind_rate_pct","type":"kpi_tile","field":"bind_rate_pct","format":"percent","header":"Bind Rate","footer":"Quotes that converted","delta_field":"bind_rate_delta_pts","delta_format":"absolute_pts","trend":true,"invert":false,"criteria":{"good":{"gte":40},"warn":{"gte":25},"danger":{"lt":25}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_premium_usd","type":"kpi_tile","field":"avg_premium_usd","format":"currency","header":"Avg. Premium","footer":"Per quoted risk","delta_field":"avg_premium_delta_usd","delta_format":"absolute_usd","trend":true,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_turnaround_s","type":"kpi_tile","field":"avg_turnaround_s","format":"seconds","header":"Avg. Turnaround","footer":"Quote-to-ready time","delta_field":"avg_turnaround_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":30},"warn":{"lte":60},"danger":{"gt":60}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"quoted_premium_usd","type":"kpi_tile","field":"quoted_premium_usd","format":"currency","header":"Total Quoted Premium","footer":"Volume this period","delta_field":"quoted_premium_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
),

-- ── Coverage Validation ───────────────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000005',
  '10000000-0000-0000-0000-000000000005',
  30,
  '[
    {"id":"policies_checked","type":"kpi_tile","field":"policies_checked","format":"number","header":"Policies Checked","footer":"Last 30 days","delta_field":"policies_checked_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":300},"warn":{"gte":150},"danger":{"lt":150}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"discrepancies_found","type":"kpi_tile","field":"discrepancies_found","format":"number","header":"Discrepancies Found","footer":"Flagged for review","delta_field":"discrepancies_found_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":20},"warn":{"lte":50},"danger":{"gt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_check_time_s","type":"kpi_tile","field":"avg_check_time_s","format":"seconds","header":"Avg. Check Time","footer":"Per policy","delta_field":"avg_check_time_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":10},"warn":{"lte":20},"danger":{"gt":20}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"auto_resolved","type":"kpi_tile","field":"auto_resolved","format":"number","header":"Auto-Resolved","footer":"Fixed without human review","delta_field":"auto_resolved_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":80},"warn":{"gte":60},"danger":{"lt":60}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"pending_review","type":"kpi_tile","field":"pending_review","format":"number","header":"Pending Review","footer":"Awaiting human action","delta_field":"pending_review_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":5},"warn":{"lte":15},"danger":{"gt":15}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
),

-- ── Renewal Review ────────────────────────────────────────────────────────────
(
  '30000000-0000-0000-0000-000000000006',
  '10000000-0000-0000-0000-000000000006',
  30,
  '[
    {"id":"renewals_prepped","type":"kpi_tile","field":"renewals_prepped","format":"number","header":"Renewals Prepped","footer":"Last 30 days","delta_field":"renewals_prepped_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":100},"warn":{"gte":50},"danger":{"lt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_premium_delta_pct","type":"kpi_tile","field":"avg_premium_delta_pct","format":"percent","header":"Avg. Premium Change","footer":"vs. expiring premium","delta_field":"avg_premium_delta_pct_delta","delta_format":"absolute_pts","trend":true,"invert":false,"criteria":{"good":{"gte":0},"warn":{"gte":0},"danger":{"lt":0}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"changes_flagged","type":"kpi_tile","field":"changes_flagged","format":"number","header":"Changes Flagged","footer":"Coverage or term changes","delta_field":"changes_flagged_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":20},"warn":{"lte":50},"danger":{"gt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"client_emails_drafted","type":"kpi_tile","field":"client_emails_drafted","format":"number","header":"Client Emails Drafted","footer":"Ready to send","delta_field":"client_emails_drafted_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":80},"warn":{"gte":50},"danger":{"lt":50}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_prep_time_s","type":"kpi_tile","field":"avg_prep_time_s","format":"seconds","header":"Avg. Prep Time","footer":"Per renewal package","delta_field":"avg_prep_time_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":30},"warn":{"lte":60},"danger":{"gt":60}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
)

ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- >>> 20260522030000_create_device_model_allocations.sql
-- ============================================================================
-- public.device_model_allocations — models allocated to each Electron device
-- Replaces old device_models table (different name; aligned with new architecture naming).
-- See: backend/docs/pod_structure.md §3 Group 5

CREATE TABLE public.device_model_allocations (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id    UUID        NOT NULL,  -- FK to devices added in migration 20260523000400
  agent_id     UUID        REFERENCES public.agents(id),
  model_name   TEXT        NOT NULL,
  allocated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  allocated_by UUID        REFERENCES public.users(id),
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX dma_device_id_idx ON public.device_model_allocations (device_id);
CREATE INDEX dma_agent_id_idx  ON public.device_model_allocations (agent_id);

ALTER TABLE public.device_model_allocations ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER device_model_allocations_updated_at
  BEFORE UPDATE ON public.device_model_allocations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260522030100_create_device_daily_analytics.sql
-- ============================================================================
-- public.device_daily_analytics — daily rollup per device
-- Replaces old device_analytics table; UNIQUE (device_id, date) for upsert safety.
-- See: backend/docs/pod_structure.md §3 Group 5

CREATE TABLE public.device_daily_analytics (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id       UUID        NOT NULL,  -- FK to devices added in migration 20260523000400 (devices created later)
  date            DATE        NOT NULL DEFAULT CURRENT_DATE,
  run_count       INT         NOT NULL DEFAULT 0,
  token_usage     INT         NOT NULL DEFAULT 0,
  cpu_load_avg    DECIMAL(5,2),
  gpu_load_avg    DECIMAL(5,2),
  error_count     INT         NOT NULL DEFAULT 0,
  sync_count      INT         NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (device_id, date)
);

CREATE INDEX dda_device_id_idx ON public.device_daily_analytics (device_id);
CREATE INDEX dda_date_idx      ON public.device_daily_analytics (date DESC);

ALTER TABLE public.device_daily_analytics ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER device_daily_analytics_updated_at
  BEFORE UPDATE ON public.device_daily_analytics
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================================
-- >>> 20260523000000_audit_logs_revoke_mutate.sql
-- ============================================================================
-- audit_logs must be INSERT-only for the authenticator role.
-- Prevents any application code from updating or deleting audit records.
REVOKE UPDATE, DELETE ON public.audit_logs FROM authenticator;


-- ============================================================================
-- >>> 20260523000100_fn_signup_atomic.sql
-- ============================================================================
-- Atomic signup: accepts invite + creates user + assigns role in one transaction.
-- Called via supabase.rpc('signup_atomic', {...})
CREATE OR REPLACE FUNCTION public.signup_atomic(
    p_token_hash  TEXT,
    p_password_hash TEXT,
    p_now         TIMESTAMPTZ DEFAULT now()
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_invite      RECORD;
    v_user_id     UUID;
    v_result      JSON;
BEGIN
    -- Lock and validate invite row
    SELECT id, email, status, expires_at
    INTO v_invite
    FROM public.invites
    WHERE token_hash = p_token_hash
      AND status = 'PENDING'
      AND expires_at > p_now
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN json_build_object('error', 'invalid_invite');
    END IF;

    -- Mark invite accepted
    UPDATE public.invites
    SET status = 'ACCEPTED'
    WHERE id = v_invite.id;

    -- Create user
    INSERT INTO public.users (email, password_hash, status)
    VALUES (v_invite.email, p_password_hash, 'pending')
    RETURNING id INTO v_user_id;

    -- Assign default role
    INSERT INTO public.user_roles (user_id, role)
    VALUES (v_user_id, 'user');

    RETURN json_build_object('user_id', v_user_id, 'email', v_invite.email);
END;
$$;

-- Only the service role (FastAPI backend) may call this function
REVOKE EXECUTE ON FUNCTION public.signup_atomic FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.signup_atomic TO service_role;


-- ============================================================================
-- >>> 20260523000200_fix_rls_custom_auth.sql
-- ============================================================================
-- RLS policies on these tables used auth.uid() which only works with Supabase Auth.
-- Since we use zero Supabase Auth (custom FastAPI RS256), auth.uid() always returns NULL
-- and every policy would silently block all access.
--
-- Fix: drop the auth.uid()-based policies and replace with service_role-only access.
-- FastAPI connects as service_role via the service role key — identity is enforced at
-- the API layer by JWT validation, not at the DB layer for these tables.

-- ── user_agents ───────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS user_agents_user ON public.user_agents;
CREATE POLICY user_agents_service ON public.user_agents
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── user_agent_stats ──────────────────────────────────────────────────────────
DROP POLICY IF EXISTS uas_user ON public.user_agent_stats;
CREATE POLICY uas_service ON public.user_agent_stats
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── agent_runs ────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS agent_runs_user ON public.agent_runs;
CREATE POLICY agent_runs_service ON public.agent_runs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── agent_run_approvals ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS ara_user ON public.agent_run_approvals;
CREATE POLICY ara_service ON public.agent_run_approvals
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── agent_access_requests ─────────────────────────────────────────────────────
DROP POLICY IF EXISTS aar_user ON public.agent_access_requests;
CREATE POLICY aar_service ON public.agent_access_requests
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ── custom_agent_requests ─────────────────────────────────────────────────────
DROP POLICY IF EXISTS car_user ON public.custom_agent_requests;
CREATE POLICY car_service ON public.custom_agent_requests
  FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ============================================================================
-- >>> 20260523000300_fix_custom_agents_fk.sql
-- ============================================================================
-- custom_agent_requests.custom_agent_id references public.custom_agents(id)
-- but the custom_agents table was not created before custom_agent_requests.
-- Fix: create custom_agents now, then restore the FK on custom_agent_requests.

CREATE TABLE IF NOT EXISTS public.custom_agents (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  title        TEXT        NOT NULL,
  description  TEXT,
  status       TEXT        NOT NULL DEFAULT 'building'
               CHECK (status IN ('building','testing','live','deprecated')),
  created_by   UUID        REFERENCES public.users(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER custom_agents_updated_at
  BEFORE UPDATE ON public.custom_agents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.custom_agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY custom_agents_service ON public.custom_agents
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- custom_agent_id column already exists from migration 020800 (no FK yet).
-- Now that custom_agents exists, add the FK constraint.
ALTER TABLE public.custom_agent_requests
  ADD CONSTRAINT custom_agent_requests_custom_agent_id_fkey
  FOREIGN KEY (custom_agent_id) REFERENCES public.custom_agents(id);


-- ============================================================================
-- >>> 20260523000400_create_devices.sql
-- ============================================================================
-- public.devices — Electron desktop devices registered with Fideon OS.
-- Authenticated via X-Device-Token header (get_device dependency).
-- Managed by admin: pending → active → suspended.

CREATE TABLE public.devices (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  device_token  TEXT        NOT NULL UNIQUE,
  os_type       TEXT,
  app_version   TEXT,
  hostname      TEXT,
  status        TEXT        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','active','suspended')),
  last_seen_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX devices_token_idx  ON public.devices (device_token);
CREATE INDEX devices_status_idx ON public.devices (status);

CREATE TRIGGER devices_updated_at
  BEFORE UPDATE ON public.devices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

CREATE POLICY devices_service ON public.devices
  FOR ALL TO service_role USING (true) WITH CHECK (true);


-- public.device_sync_logs — check-in and sync event log per device.

CREATE TABLE public.device_sync_logs (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id   UUID        NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  sync_type   TEXT        NOT NULL,
  status      TEXT        NOT NULL DEFAULT 'success'
              CHECK (status IN ('success','failure')),
  details     JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX dsl_device_id_idx ON public.device_sync_logs (device_id);
CREATE INDEX dsl_created_at_idx ON public.device_sync_logs (created_at DESC);

ALTER TABLE public.device_sync_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY dsl_service ON public.device_sync_logs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- device_model_allocations.device_id FK was deferred until devices existed
ALTER TABLE public.device_model_allocations
  ADD CONSTRAINT dma_device_id_fkey
  FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE;

-- device_daily_analytics.device_id FK was deferred until devices existed
ALTER TABLE public.device_daily_analytics
  ADD CONSTRAINT dda_device_id_fkey
  FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE CASCADE;


-- ============================================================================
-- >>> 20260524000000_audit_logs_resource_type_not_null.sql
-- ============================================================================
-- Align audit_logs with Auth_Module_Plan.md §2.9:
--   - resource_type must be NOT NULL (every audit write categorizes its resource;
--     both writers — auth/dependencies.py and routers/auth.py._audit — always supply it).
--   - index renamed audit_logs_created_idx → audit_logs_created_at_idx to match spec.

-- Backfill any legacy NULLs so the NOT NULL constraint can be applied safely.
UPDATE public.audit_logs SET resource_type = 'unknown' WHERE resource_type IS NULL;

ALTER TABLE public.audit_logs
  ALTER COLUMN resource_type SET NOT NULL;

-- Spec-aligned index name.
ALTER INDEX IF EXISTS public.audit_logs_created_idx RENAME TO audit_logs_created_at_idx;


-- ============================================================================
-- >>> 20260524010000_agent_runs_confidence_scale.sql
-- ============================================================================
-- Lock agent_runs.confidence to the canonical 0–1 probability scale.
--
-- The entire frontend (Dashboard, PodDashboard, Work, governance, pod analytics)
-- renders confidence as `Math.round(confidence * 100)%`, and every writer
-- (demo.py, DesktopRuntime, GPU worker) emits a 0–1 value. The column was
-- DECIMAL(5,2) with no constraint, leaving the scale ambiguous and allowing a
-- stray 95.0 to render as 9500%. This pins the contract in the database.

-- Clamp any pre-existing out-of-range rows (e.g. a worker that wrote 0–100)
-- back into 0–1 before applying the constraint, so the migration is safe.
UPDATE public.agent_runs
   SET confidence = confidence / 100.0
 WHERE confidence IS NOT NULL
   AND confidence > 1;

-- Widen precision: a 0–1 probability keeps 4 decimals (DECIMAL(5,2) kept only 2).
ALTER TABLE public.agent_runs
  ALTER COLUMN confidence TYPE DECIMAL(5,4);

ALTER TABLE public.agent_runs
  ADD CONSTRAINT agent_runs_confidence_range
  CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1));


-- ============================================================================
-- >>> 20260524020000_seed_fideon_admin.sql
-- ============================================================================
-- Seed the first Fideon admin (TESTING).
-- Email:    fideonadmin@gmail.com
-- Password: Admin@12345   (Argon2id hash below; verified against the backend hasher)
--
-- This account is listed in OTP_BYPASS_EMAILS so it signs in with password only.
-- All invited/normal users still go through the standard OTP flow.
-- Idempotent: safe to re-run (updates the existing row instead of erroring).

DO $$
DECLARE
  v_admin_id UUID;
BEGIN
  INSERT INTO public.users (
    email,
    password_hash,
    status,
    email_verified_at,
    full_name
  )
  VALUES (
    'fideonadmin@gmail.com',
    '$argon2id$v=19$m=65536,t=3,p=4$E4PWSjYunISt2o96TK74pg$LmaZqxloM2dA62bCrvWvTal6/cv0cMfNDAHGpPFPNu0',
    'active',
    now(),
    'Fideon Admin'
  )
  ON CONFLICT (email) DO UPDATE
    SET
      password_hash     = EXCLUDED.password_hash,
      status            = 'active',
      email_verified_at = COALESCE(public.users.email_verified_at, now()),
      full_name         = EXCLUDED.full_name,
      updated_at        = now();

  SELECT id INTO v_admin_id FROM public.users WHERE email = 'fideonadmin@gmail.com';

  INSERT INTO public.user_roles (user_id, role)
  VALUES (v_admin_id, 'admin')
  ON CONFLICT (user_id) DO UPDATE
    SET role = 'admin';

  RAISE NOTICE 'Fideon Admin seeded: id=%, email=fideonadmin@gmail.com', v_admin_id;
END $$;


-- ============================================================================
-- >>> 20260525000000_seed_acord_form_extraction_agent.sql
-- ============================================================================
-- Add the ACORD Form Extraction agent to the catalog (marketplace).
-- Mirrors the 6 seeded live agents: agents row + agent_versions v1.0.0 + dashboard template.
-- Stable UUIDs follow the existing ...0007 slot convention.
-- See: backend/docs/pod_structure.md §10 Agent Catalog Reference

-- 1) Catalog row. status='live' + the /agents/marketplace endpoint filter
--    (status IN ('live','beta','coming_soon')) makes it appear in the marketplace.
INSERT INTO public.agents (id, keyword, name, description, domain, tagline, status)
VALUES (
  '10000000-0000-0000-0000-000000000007',
  'acord-form-extraction',
  'ACORD Form Extraction',
  'Extracts structured data from ACORD forms (125, 126, 140, etc.) — parsing fields, validating values, and outputting clean records for downstream workflows.',
  'insurance',
  'Turn any ACORD form into structured data, instantly.',
  'live'
)
ON CONFLICT (id) DO NOTHING;

-- 2) Active version v1.0.0 with input/output schemas.
INSERT INTO public.agent_versions
  (id, agent_id, version, is_active, input_schema, output_schema)
VALUES (
  '20000000-0000-0000-0000-000000000007',
  '10000000-0000-0000-0000-000000000007',
  '1.0.0', true,
  '{"document_ids":{"type":"array","items":"string","required":true},"form_types":{"type":"array","items":"string","required":false,"enum":["acord_125","acord_126","acord_127","acord_130","acord_140","acord_25"]},"validate_fields":{"type":"boolean","required":false}}',
  '{"forms_extracted":{"type":"number"},"fields_extracted":{"type":"number"},"extraction_accuracy_pct":{"type":"number"},"avg_extraction_time_s":{"type":"number"},"manual_corrections":{"type":"number"},"completed_at":{"type":"timestamp"}}'
)
ON CONFLICT (id) DO NOTHING;

-- 3) Back-fill the catalog row's current_version_id.
UPDATE public.agents
  SET current_version_id = '20000000-0000-0000-0000-000000000007'
  WHERE id = '10000000-0000-0000-0000-000000000007';

-- 4) Dashboard template (KPI tiles). Single-tab, mirrors the other agents' widget shape.
INSERT INTO public.agent_dashboard_templates
  (id, agent_id, comparison_period_days, widgets, tabs)
VALUES (
  '30000000-0000-0000-0000-000000000007',
  '10000000-0000-0000-0000-000000000007',
  30,
  '[
    {"id":"forms_extracted","type":"kpi_tile","field":"forms_extracted","format":"number","header":"Forms Extracted","footer":"Last 30 days","delta_field":"forms_extracted_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":300},"warn":{"gte":150},"danger":{"lt":150}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"extraction_accuracy_pct","type":"kpi_tile","field":"extraction_accuracy_pct","format":"percent","header":"Extraction Accuracy","footer":"Validated field accuracy","delta_field":"extraction_accuracy_delta_pts","delta_format":"absolute_pts","trend":true,"invert":false,"criteria":{"good":{"gte":95},"warn":{"gte":85},"danger":{"lt":85}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"fields_extracted","type":"kpi_tile","field":"fields_extracted","format":"number","header":"Fields Extracted","footer":"Across all forms","delta_field":"fields_extracted_delta_pct","delta_format":"percent","trend":true,"invert":false,"criteria":{"good":{"gte":5000},"warn":{"gte":2000},"danger":{"lt":2000}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"avg_extraction_time_s","type":"kpi_tile","field":"avg_extraction_time_s","format":"seconds","header":"Avg. Extraction Time","footer":"Per form","delta_field":"avg_extraction_time_s_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":10},"warn":{"lte":25},"danger":{"gt":25}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}},
    {"id":"manual_corrections","type":"kpi_tile","field":"manual_corrections","format":"number","header":"Manual Corrections","footer":"Lower is better","delta_field":"manual_corrections_delta","delta_format":"absolute","trend":true,"invert":true,"criteria":{"good":{"lte":10},"warn":{"lte":30},"danger":{"gt":30}},"color_indicator":{"good":"#15803d","warn":"#d97706","danger":"#dc2626"}}
  ]',
  NULL
)
ON CONFLICT (id) DO NOTHING;


COMMIT;
